### ISSUE TITLE
"Huston, CNOT have a situation..."

### ISSUE THREAD

**Issue by mvcm66** [corbett/QuantumComputing#10]
Actually in the last weeks I have spent many (almost all) of my free hours testing and trying to understand how QuantumComputer.py works, even to try to help in some way.

Maybe someone might ask, "But why? This app is just an experiment! ".

Exactly! Precisely for this reason, because it was designed and developed to study quantum logic.

QuantumComputer.py is a laboratory, and things do not always (almost never) go exactly as we planned in the lab experiments. In addition to the reasons for studying and researching, there is another: I love the idea of having a quantum computer in my pocket!      :)

QuantumComputer.py is a complex and robust application, encoded in a just single file! 
You can send it attached in a whatsapp message! Even though most people have no interest in it, or even understand what it is ...      :)

But this study of Dr. Christine has the potential to be easily distributed, shared by students around the world, making quantum computing as popular in this early 21st century as the Abacus was 4,000 years ago.

Anyway, I have plenty of reasons to spend my free hours on this project.   :)

Now, I found a weird result from a banal test. 
May be this could be useful to solve some logic constraints of CNOT.

Follows the test done in the IBM Quantum Simulator:
Note that Q0 set to |1> with X gate.
![x0_score](https://cloud.githubusercontent.com/assets/26702059/25571428/e8201e12-2e05-11e7-80c3-2c3e8f397aa3.png)

The QASM code:
![x0_qasm](https://cloud.githubusercontent.com/assets/26702059/25571434/f5d3a182-2e05-11e7-9cc5-90273138535c.png)

And the result from IBM Quantum Simulator:
![x0_ibm_qe](https://cloud.githubusercontent.com/assets/26702059/25571456/35a47890-2e06-11e7-93a7-7c4bee6e41c0.png)

IBM show it in binary order 43210 as “00001”   (or “001”)
In reverse (natural) order 01234, the result will must be “10000” (or “100”)

But the QuantumComputer.py result is different...  "010"
![x0](https://cloud.githubusercontent.com/assets/26702059/25571480/91c581c8-2e06-11e7-8e89-13f7d55ab682.png)

This is the Python source code used in all tests:
[CNOT Situation.txt](https://github.com/corbett/QuantumComputing/files/967301/CNOT.Situation.txt)

See the screen of source code used:
![x0py](https://cloud.githubusercontent.com/assets/26702059/25571562/60fb2b50-2e07-11e7-918b-51076ba06ff2.png)

When the Q1 is set to |1> 
![x1_score](https://cloud.githubusercontent.com/assets/26702059/25571664/725074f4-2e08-11e7-8370-66a27b0f990f.png)

IBM show it in binary order 43210 as “00010”   (or “010”)
In reverse (natural) order 01234, the result will must be “01000” (or “010”)
![x1_ibm_qe](https://cloud.githubusercontent.com/assets/26702059/25571694/a605e900-2e08-11e7-9c87-77a40bf8b289.png)

But the QuantumComputer.py result is different...  "100"
![x1](https://cloud.githubusercontent.com/assets/26702059/25571776/a0ebbd5e-2e09-11e7-9e57-dfba1af61b97.png)

When the Q2 is set to |1> 
![x2_score](https://cloud.githubusercontent.com/assets/26702059/25571829/3cb629ae-2e0a-11e7-9be4-81e8a701e801.png)

IBM show it in binary order 43210 as “00111”   (or “111”)
In reverse (natural) order 01234, the result will must be “11100” (or “111”)
![x2_ibm_qe](https://cloud.githubusercontent.com/assets/26702059/25571857/c1285e5a-2e0a-11e7-85ec-347bedabc696.png)

In this test QuantumComputer.py result is EQUAL to IBM !   "111"
![x2](https://cloud.githubusercontent.com/assets/26702059/25571879/fed67aac-2e0a-11e7-80b1-f396ccc11dd1.png)

I hope these test cases can shed some light on the CNOT algorithm.

**Comment by rtvuser1** [comment]
Hi Marcus,
Did you ever resolve this issue ?

**Comment by marcus-mello** [comment]
Yes Tom,

I solved it, but I was expecting some interaction with the other
collaborators before publishing here.

I had to make some severe modifications and I do not know exactly how to
use Github to publish it.

What is the best way to post the modified source here, in this case?

Please contact me using Linkedin or Facebook to let us interchange ideas and sources.

A​tt
Marcus Mello
http://www.linkedin.com/in/marcusmello/




2017-12-06 14:59 GMT+00:00 Tom Lubinski <notifications@github.com>:
