### ISSUE TITLE
Found it very hard to do simple computing programming 

### ISSUE THREAD

**Issue by kwccoin** [corbett/QuantumComputing#18]
I can run it even in Pythonista.  But given the large size of the program, it will be better if one can have separate files to run it.  So far not successful and have to run my qm as test by cloning one of the test as source.  And sometimes it does not work. I will give example whilst I continue he struggle.  Js has an drag and drop n ipad.  Hope python has one with Pythonista even if just text.

**Comment by marcus-mello** [comment]
Hi, I installed it in my PC, and then needed to install a lot of PIP packages to run it. 
Works well. 
I coded a environment to manage my programs and I use the Corbett QC as a subroutine to run them.

**Comment by kwccoin** [comment]
I finally get it work; thanks!!

**Comment by kwccoin** [comment]
For my future me.  There is a minor issue with the README (need a qc.reset() or qc = Q....).  Other than that, my code is only provide a bit more message for testing.

[ibm_5q_callProgram copy.py.txt](https://github.com/corbett/QuantumComputing/files/9793718/ibm_5q_callProgram.copy.py.txt)
